import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between gap-2 w-full">
          <Link href="/">Home</Link>
          <section>
            <Link href="/category">Categorías</Link>
            <Link href="/publish">Publicar</Link>
          </section>
        </nav>
        {children}
      </body>
    </html>
  )
}
